# Generated by Django 6.1.2 on 2026-10-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
